language: node_js
node_js:
  - "5.7.1"
before_install:
  - node -v
  - ruby -v
  - if [ -f /Gemfile ]; then echo "Gemfile found" fi
  - rvm install 2.2.2
  - gem install bundler
  - bundle install
script:
  - node -v
  - ruby -v
  - ./build.sh
  - ./deploy-travis.sh
